// Personal ledger stays private on this device. Shared links contain group snapshots only.
let ledger=[];let ledgerEdit=null;let sharedGroup=null;
try{ledger=JSON.parse(localStorage.getItem('bsplit_ledger')||'[]');}catch{}
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
document.head.insertAdjacentHTML('beforeend',`<style>
.finance-wrap{max-width:900px;margin:auto;padding:20px}.finance-nav,.month-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-bottom:18px}.finance-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.finance-stats .num{font-size:1.2rem}.ledger-row{display:flex;align-items:center;gap:12px;background:var(--surface);border-radius:12px;padding:15px;margin-bottom:8px}.ledger-row .info{flex:1;min-width:0}.ledger-row small{color:var(--muted)}input[type=date],input[type=month]{background:var(--surface);color:var(--text);border:1px solid var(--border);padding:10px;border-radius:10px;font:inherit;color-scheme:dark}.trend-row{display:grid;grid-template-columns:80px 1fr 110px;gap:8px;align-items:center;font-size:.8rem;margin:12px 0}.track{height:10px;background:var(--card);border-radius:10px;overflow:hidden}.fill{height:100%}#shared-notice{padding:14px 20px;background:rgba(245,166,35,.12);font-size:.85rem}.share-link{min-height:100px;word-break:break-all}button:focus-visible{outline:2px solid var(--accent2);outline-offset:3px}@media(max-width:480px){.finance-stats{grid-template-columns:1fr}.ledger-row{flex-wrap:wrap}.trend-row{grid-template-columns:70px 1fr 100px}}@media(min-width:900px){#screen-home>div,#screen-group>.page{max-width:900px;margin:auto}}</style>`);
document.querySelector('#screen-home header').insertAdjacentHTML('afterend',`<nav class="finance-nav" style="padding:16px 20px"><button class="btn" onclick="showFinance()">💰 รายรับ–รายจ่ายของฉัน</button><span style="color:var(--muted);font-size:.8rem">ดูยอดรายเดือนและเงินที่ติดลบ</span></nav>`);
document.querySelector('#screen-group .header-inner').insertAdjacentHTML('beforeend',`<button class="btn secondary btn-sm" onclick="shareCurrentGroup()">🔗 แชร์</button>`);
document.body.insertAdjacentHTML('beforeend',`<section id="screen-finance" style="display:none"><header><div class="header-inner"><button class="back-btn" onclick="goHome()" aria-label="กลับ">←</button><div class="header-title"><h1>💰 เงินของฉัน</h1><p>รายรับ–รายจ่ายรายเดือน · เก็บส่วนตัวในเครื่องนี้</p></div></div></header><div class="finance-wrap"><div class="month-bar"><button class="btn secondary" onclick="moveMonth(-1)" aria-label="เดือนก่อน">←</button><label for="finance-month">เดือน</label><input type="month" id="finance-month" onchange="renderFinance()"><button class="btn secondary" onclick="moveMonth(1)" aria-label="เดือนถัดไป">→</button><button class="btn" onclick="editLedger()">+ บันทึกรายการ</button></div><div id="finance-summary"></div><div class="section-title">ภาพรวม 6 เดือน · ยอดสุทธิ</div><div id="finance-trend"></div><div class="section-title">รายการในเดือนนี้</div><div id="finance-list"></div><button class="btn secondary" onclick="backupLedger()">ดาวน์โหลดข้อมูลสำรอง</button><p style="font-size:.8rem;color:var(--muted);margin-top:14px">ยอดสุทธิ = รายรับ − รายจ่ายของเดือนที่เลือก ไม่รวมยอดยกมาหรือยอดหารกับเพื่อน ข้อมูลส่วนตัวนี้ไม่รวมในลิงก์แชร์กลุ่ม การล้างข้อมูลเบราว์เซอร์จะลบข้อมูลในเครื่องนี้</p></div></section>
<div class="modal-overlay" id="finance-modal"><form class="modal" onsubmit="submitLedger(event)"><button type="button" class="modal-close" onclick="closeFinanceModal()" aria-label="ปิด">✕</button><h2 id="finance-form-title">บันทึกรายการ</h2><div class="field"><label for="finance-type">ประเภท</label><select id="finance-type"><option value="expense">รายจ่าย</option><option value="income">รายรับ</option></select></div><div class="field"><label for="finance-name">ชื่อรายการ</label><input type="text" id="finance-name" maxlength="100" required></div><div class="field"><label for="finance-amount">จำนวนเงิน (บาท)</label><input type="number" id="finance-amount" min="0.01" max="999999999" step="0.01" required></div><div class="field"><label for="finance-date">วันที่</label><input type="date" id="finance-date" required></div><div class="field"><label for="finance-category">หมวดหมู่</label><select id="finance-category"><option>อาหาร</option><option>เดินทาง</option><option>ที่พัก / บิล</option><option>ช้อปปิ้ง</option><option>สุขภาพ</option><option>เงินเดือน</option><option>รายได้เสริม</option><option>อื่น ๆ</option></select></div><div class="field"><label for="finance-note">หมายเหตุ</label><textarea id="finance-note" maxlength="500"></textarea></div><button class="btn" style="width:100%">บันทึก</button></form></div>
<div class="modal-overlay" id="share-dialog"><div class="modal"><button class="modal-close" onclick="document.getElementById('share-dialog').classList.remove('open')" aria-label="ปิด">✕</button><h2>แชร์ข้อมูลกลุ่ม</h2><p style="color:var(--muted);font-size:.85rem;margin-bottom:14px">เพื่อนเห็นรายการ ยอดหาร และใครต้องโอนให้ใคร ณ ตอนที่แชร์ ทุกคนที่มีลิงก์เปิดดูได้ ไม่รวมรูปสลิปและข้อมูลเงินส่วนตัว หากรายการเปลี่ยนให้แชร์ลิงก์ใหม่</p><textarea id="group-share-link" class="share-link" readonly aria-label="ลิงก์แชร์"></textarea><button class="btn" style="margin-top:12px" onclick="copyGroupLink()">คัดลอกลิงก์</button></div></div>`);
const baseHome=goHome;goHome=function(){sharedGroup=null;document.getElementById('screen-finance').style.display='none';document.getElementById('shared-notice')?.remove();document.querySelector('#tab-members .add-row').style.display='flex';document.querySelector('#screen-group .header-inner').querySelector('[title="ตั้งค่ากลุ่ม"]').style.display='';baseHome();};
const baseG=g;g=function(){return sharedGroup||baseG();};
function showFinance(){goHome();document.getElementById('screen-home').style.display='none';document.getElementById('screen-finance').style.display='block';document.getElementById('finance-month').value ||=localDate().slice(0,7);renderFinance();}
function monthTotals(month){let income=0,expense=0;for(const t of ledger.filter(t=>t.date.slice(0,7)===month)){if(t.type==='income')income+=t.cents;else expense+=t.cents;}return {income,expense,net:income-expense};}
function renderFinance(){const month=document.getElementById('finance-month').value;if(!/^\d{4}-\d{2}$/.test(month))return;const t=monthTotals(month);document.getElementById('finance-summary').innerHTML=`<div class="finance-stats">${[['รายรับ',t.income,'var(--green)'],['รายจ่าย',t.expense,'var(--red)'],[t.net<0?'ติดลบ':'คงเหลือ',Math.abs(t.net),t.net<0?'var(--red)':'var(--green)']].map(([label,cents,color])=>`<div class="stat-box"><div class="lbl">${label}</div><div class="num" style="color:${color}">฿${fmt(cents/100)}</div></div>`).join('')}</div>`;const rows=ledger.filter(x=>x.date.slice(0,7)===month).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('finance-list').innerHTML=rows.length?rows.map(x=>`<div class="ledger-row"><div class="info"><strong>${escapeHTML(x.name)}</strong><br><small>${escapeHTML(x.date)} · ${escapeHTML(x.category)}${x.note?' · '+escapeHTML(x.note):''}</small></div><strong style="color:${x.type==='income'?'var(--green)':'var(--red)'}">${x.type==='income'?'+':'−'}฿${fmt(x.cents/100)}</strong><button class="btn secondary btn-sm" onclick="editLedger('${x.id}')" aria-label="แก้ไข">✏️</button><button class="btn secondary btn-sm" onclick="removeLedger('${x.id}')" aria-label="ลบ">🗑</button></div>`).join(''):'<div class="empty-state"><div class="icon">📝</div><p>ยังไม่มีรายการในเดือนนี้<br>กดบันทึกรายการเพื่อเริ่มต้น</p></div>';const [year,m]=month.split('-').map(Number);const months=Array.from({length:6},(_,i)=>{const d=new Date(year,m-6+i,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;});const max=Math.max(1,...months.map(m=>Math.abs(monthTotals(m).net)));document.getElementById('finance-trend').innerHTML=months.map(m=>{const v=monthTotals(m).net;return `<div class="trend-row"><span>${m}</span><div class="track"><div class="fill" style="width:${Math.abs(v)/max*100}%;background:${v<0?'var(--red)':'var(--green)'}"></div></div><span style="text-align:right;color:${v<0?'var(--red)':'var(--green)'}">${v<0?'−':'+'}฿${fmt(Math.abs(v)/100)}</span></div>`;}).join('');}
function moveMonth(delta){const input=document.getElementById('finance-month');const [y,m]=input.value.split('-').map(Number);const d=new Date(y,m-1+delta,1);input.value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;renderFinance();}
function editLedger(id){const t=ledger.find(x=>x.id===id);ledgerEdit=t?.id||null;document.getElementById('finance-form-title').textContent=t?'แก้ไขรายการ':'บันทึกรายการ';for(const key of ['name','type','date','category','note'])document.getElementById('finance-'+key).value=t?.[key]||(key==='type'?'expense':key==='date'?document.getElementById('finance-month').value+'-'+(document.getElementById('finance-month').value===localDate().slice(0,7)?localDate().slice(8):'01'):key==='category'?'อาหาร':'');document.getElementById('finance-amount').value=t?t.cents/100:'';document.getElementById('finance-modal').classList.add('open');document.getElementById('finance-name').focus();}
function closeFinanceModal(){document.getElementById('finance-modal').classList.remove('open');}
function persistLedger(next){try{localStorage.setItem('bsplit_ledger',JSON.stringify(next));ledger=next;return true;}catch{showAlert('บันทึกไม่สำเร็จ พื้นที่ในเครื่องอาจเต็ม กรุณาดาวน์โหลดข้อมูลสำรอง');return false;}}
function submitLedger(event){event.preventDefault();const get=k=>document.getElementById('finance-'+k).value;const cents=Math.round(Number(get('amount'))*100);const date=get('date');if(!get('name').trim()||!Number.isSafeInteger(cents)||cents<=0||cents>99999999900||!/^\d{4}-\d{2}-\d{2}$/.test(date))return showAlert('ตรวจสอบชื่อ จำนวนเงิน และวันที่');const t={id:ledgerEdit||crypto.randomUUID(),name:get('name').trim(),type:get('type'),cents,date,category:get('category'),note:get('note').trim()};const next=ledgerEdit?ledger.map(x=>x.id===ledgerEdit?t:x):[...ledger,t];if(persistLedger(next)){document.getElementById('finance-month').value=date.slice(0,7);closeFinanceModal();renderFinance();}}
function removeLedger(id){if(confirm('ลบรายการนี้หรือไม่?')&&persistLedger(ledger.filter(x=>x.id!==id)))renderFinance();}
function backupLedger(){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,transactions:ledger},null,2)],{type:'application/json'}));a.href=url;a.download='my-finance-'+localDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function shareCurrentGroup(){try{const group=g();const data={version:1,group:{...group,expenses:group.expenses.map(({slips,...e})=>({...e,slips:[]}))}};const bytes=new TextEncoder().encode(JSON.stringify(data));const compressed=await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();const encoded=btoa(Array.from(new Uint8Array(compressed),b=>String.fromCharCode(b)).join('')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=location.origin+location.pathname+'#group='+encoded;if(url.length>24000)return showAlert('กลุ่มนี้มีข้อมูลมากเกินไปสำหรับลิงก์แชร์ กรุณาแบ่งเป็นกลุ่มย่อย');document.getElementById('group-share-link').value=url;document.getElementById('share-dialog').classList.add('open');}catch{showAlert('เบราว์เซอร์นี้สร้างลิงก์ไม่ได้ กรุณาใช้ Chrome, Edge หรือ Safari รุ่นล่าสุด');}}
async function copyGroupLink(){const input=document.getElementById('group-share-link');try{await navigator.clipboard.writeText(input.value);showAlert('คัดลอกลิงก์แล้ว ส่งให้เพื่อนได้เลย','✅');}catch{input.focus();input.select();showAlert('เลือกลิงก์แล้ว กดคัดลอกเพื่อส่งให้เพื่อน');}}
// Block every write entrypoint on the shared snapshot.
for(const name of ['openEditGroupModal','saveGroup','deleteGroup','addMember','removeMember','openAddModal','openEditModal','saveExpense','deleteExpense']){const original=window[name];window[name]=function(...args){if(sharedGroup)return showAlert('ลิงก์นี้สำหรับดูข้อมูล ณ ตอนที่แชร์เท่านั้น');return original(...args);};}
const originalTab=switchTab;switchTab=function(name){originalTab(name);if(sharedGroup){document.getElementById('fab-btn').style.display='none';document.querySelectorAll('#screen-group .del,#expense-list button').forEach(el=>el.style.display='none');}};
const originalMembers=renderMembers;renderMembers=function(){if(!sharedGroup)return originalMembers();document.getElementById('member-chips').innerHTML=sharedGroup.members.map(m=>`<div class="chip">${m}</div>`).join('');};
async function readSharedGroup(){if(!location.hash.startsWith('#group='))return;try{const encoded=location.hash.slice(7);if(encoded.length>24000)throw Error();const raw=atob(encoded.replace(/-/g,'+').replace(/_/g,'/'));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));const reader=stream.getReader();let chunks=[],size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>500000){await reader.cancel();throw Error();}chunks.push(value);}const obj=JSON.parse(await new Blob(chunks).text());const v=obj.group;if(obj.version!==1||!v||typeof v.name!=='string'||!Array.isArray(v.members)||v.members.length>200||!v.members.every(m=>typeof m==='string')||!Array.isArray(v.expenses)||v.expenses.length>1000)throw Error();for(const e of v.expenses){if(typeof e.name!=='string'||!Number.isFinite(e.amount)||e.amount<=0||!v.members.includes(e.payer)||!Array.isArray(e.participants)||!e.participants.length||!e.participants.every(p=>v.members.includes(p)))throw Error();if(e.splitMode==='custom'&&(!e.customAmounts||e.participants.some(p=>!Number.isFinite(e.customAmounts[p])||e.customAmounts[p]<0)||Math.abs(e.participants.reduce((a,p)=>a+e.customAmounts[p],0)-e.amount)>.01))throw Error();}
// Escape external text before legacy template rendering. IDs never enter HTML from links.
const names=new Map(v.members.map(n=>[n,escapeHTML(n)]));sharedGroup={id:'shared',name:escapeHTML(v.name),icon:escapeHTML(v.icon||'👥'),members:v.members.map(n=>names.get(n)),expenses:v.expenses.map((e,i)=>({...e,id:'shared-'+i,name:escapeHTML(e.name),note:escapeHTML(e.note||''),date:escapeHTML(e.date||''),payer:names.get(e.payer),participants:e.participants.map(p=>names.get(p)),customAmounts:Object.fromEntries(Object.entries(e.customAmounts||{}).map(([k,val])=>[names.get(k),val])),slips:[]}))};openGroup('shared');document.getElementById('screen-group').querySelector('.tabs').insertAdjacentHTML('beforebegin','<div id="shared-notice">👀 ดูข้อมูล ณ ตอนที่แชร์ · หากรายการเปลี่ยน ให้เจ้าของส่งลิงก์ใหม่</div>');document.querySelector('#tab-members .add-row').style.display='none';document.querySelector('#screen-group [title="ตั้งค่ากลุ่ม"]').style.display='none';switchTab('result');}catch{showAlert('ลิงก์แชร์ไม่ถูกต้องหรือข้อมูลเสียหาย กรุณาขอลิงก์ใหม่');}}
readSharedGroup();
